TaskTimer/Areas/Admin/Controllers/AdminHomeController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TaskTimer.Areas.Admin.Models;
using TaskTimer.Models;

namespace TaskTimer.Areas.Admin.Controllers
{
    public class AdminHomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult SitePages()
        {
            var db = new CustomMembershipDB();
            return View(db.SiteMainPages);
        }
        public ActionResult SitePagesAddNew(int id)
        {
            if (id == -1) //new page
                return View(new SiteMainPages());
            var db = new CustomMembershipDB();
            var editPage = db.SiteMainPages.FirstOrDefault(p => p.Id == id);
            if (editPage == null)
                editPage = new SiteMainPages();
            return View(editPage);
        }
        [HttpPost]
        public ActionResult SitePagesAddNew(SiteMainPages newPage)
        {
            //upload files
            var saveToDirectory = AppDomain.CurrentDomain.BaseDirectory + "Images\\Site Pages\\";
            foreach (string file in Request.Files)
            {
                HttpPostedFileBase hpf = Request.Files[file] as HttpPostedFileBase;
                if (hpf.ContentLength == 0)
                    continue;
                var saveFileName = Path.GetFileName(hpf.FileName);
                saveFileName = AdminHelper.GetUniqueFileName(saveToDirectory, saveFileName);
                string savedFileName = Path.Combine(
                  saveToDirectory,
                  saveFileName);
                hpf.SaveAs(savedFileName);
                if (file.Equals("TitleImage"))
                    newPage.TitleImage = saveFileName;
                else if (file.Equals("BodyImage"))
                    newPage.BodyImage = saveFileName;
                else  if (file.Equals("FooterImage"))
                    newPage.FooterImage = saveFileName;
            }
            var db = new CustomMembershipDB();
            db.SiteMainPages.Add(newPage);
            db.SaveChanges();
            return RedirectToAction("SitePages");
        }
        public ActionResult SitePagesDelete(int id)
        {
            var db = new CustomMembershipDB();
            var deletePage = db.SiteMainPages.FirstOrDefault(p => p.Id == id);
            if (deletePage != null)
            {
                db.SiteMainPages.Remove(deletePage);
                db.SaveChanges();
            }
            return RedirectToAction("SitePages");
        }
    }
}

TaskTimer/Controllers/SitePagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TaskTimer.Models;

namespace TaskTimer.Controllers
{
    public class SitePagesController : Controller
    {
        //
        // GET: /SitePages/

        public ActionResult Index(int id)
        {
            var db = new CustomMembershipDB();
            var page = db.SiteMainPages.FirstOrDefault(p => p.Id == id);
            if (page == null)
                page = new SiteMainPages();
            return View(page);
        }

    }
}

TaskTimer/Areas/Admin/Views/AdminHome/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<style type="text/css">
   
</style>

TaskTimer/Areas/Admin/Views/AdminHome/SitePages.cshtml
@model System.Data.Entity.DbSet<TaskTimer.Models.SiteMainPages>
@{
    ViewBag.Title = "SitePages";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Site pages</h2>
@Html.ActionLink("Add new site page", "SitePagesAddNew", "AdminHome", new { id = -1 }, null)

<table id="myTable" class="tablesorter">
    <thead>
    <tr>
        <th>
            ID
        </th>
        <th>
            MetaTag
        </th>
        <th>
            Page DescriptionTag
        </th>
        <th>
            Title
        </th>
        <th>
            Body
        </th>
        <th>
            Footer
        </th>
        <th>
            Title Image
        </th>
        <th>
            Body Image
        </th>
         <th>
            Footer Image
        </th>
        <th>
            Actions
        </th>
    </tr>
    </thead>

    <tbody>
    @foreach (var item in Model) {
    <tr>
        <td>
            <div>
                @Html.DisplayFor(modelItem => item.Id)
            </div>
        </td>
        <td>
            <div>
                @Html.DisplayFor(modelItem => item.MetaTag)
            </div>
        </td>
        <td>
            <div>
                @Html.DisplayFor(modelItem => item.DescriptionTag)
            </div>
        </td>
        <td>
            <div>
                @Html.DisplayFor(modelItem => item.Title)
            </div>
        </td>

        <td>
            <div>
                @Html.DisplayFor(modelItem => item.Body)
            </div>
        </td>
        <td>
            <div>
                @Html.DisplayFor(modelItem => item.Footer)
            </div>
        </td>
        <td>
            <div>
                @Html.DisplayFor(modelItem => item.TitleImage)
            </div>
        </td>
        <td>
            <div>
                @Html.DisplayFor(modelItem => item.BodyImage)
            </div>
        </td>
        <td>
            <div>
                @Html.DisplayFor(modelItem => item.FooterImage)
            </div>
        </td>
        <td>
            <div>
                @Html.ActionLink("Site", "Index", "SitePages", new { area = "", id = item.Id }, null) |
                @Html.ActionLink("Edit", "SitePagesAddNew", new { id = item.Id }) |
                @Html.ActionLink("Delete", "SitePagesDelete", new { id = item.Id })
            </div>
        </td>
    </tr>
    }
        </tbody>
</table>

TaskTimer/Areas/Admin/Views/AdminHome/SitePagesAddNew.cshtml
@model TaskTimer.Models.SiteMainPages

@{
    ViewBag.Title = "SitePagesAddNew";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Add new site page</h2>

@*<div id="addNewPage"> </div>*@
@using (Html.BeginForm("SitePagesAddNew", "AdminHome", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary()

    <fieldset class="addNewPage">
        <legend>New Page Form</legend>
        <ol>
            <li>
                @Html.LabelFor(m => m.MetaTag)
                @Html.TextBoxFor(m => m.MetaTag)
            </li>
            <li>
                @Html.LabelFor(m => m.DescriptionTag)
                @Html.TextBoxFor(m => m.DescriptionTag)
            </li>
            <li>
                @Html.LabelFor(m => m.TitleTag)
                @Html.TextBoxFor(m => m.TitleTag)
            </li>
            <li>
                @Html.LabelFor(m => m.Title)
                @Html.TextBoxFor(m => m.Title)
            </li>
            <li>
                @Html.LabelFor(m => m.TitleImage)
                <input type="file" name="TitleImage" />
            @*    @FileUpload.GetHtml(
                    initialNumberOfFiles:1,
                    allowMoreFilesToBeAdded:false,
                    includeFormTag:true,
                    uploadText:"Upload")*@
            </li>
            <li>
                @Html.LabelFor(m => m.Body)
                @Html.TextAreaFor(m => m.Body)
            </li>
            <li>
                @Html.LabelFor(m => m.BodyImage)
                 <input type="file" name="BodyImage" />
            </li>
            <li>
                @Html.LabelFor(m => m.Footer)
                @Html.TextBoxFor(m => m.Footer)
            </li>
            <li>
                @Html.LabelFor(m => m.FooterImage)
                <input type="file" name="FooterImage" />
            </li>
@*            <li>
                @Html.CheckBoxFor(m => m.IsEmailRegConform)
                @Html.LabelFor(m => m.IsEmailRegConform, new { style = "display: inline-block;" })
            </li>*@
        </ol>
        <input type="submit" value="Save new page" />
    </fieldset>
}